<?xml version="1.0"?>
<robot name="robot" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- Constants for robot dimensions -->
  <xacro:property name="head_mass" value="0.250" />
  <xacro:property name="head_height" value="0.05" />
  <xacro:property name="head_size" value="0.100" />
  <xacro:property name="joint_mass" value="0.100" />
  <xacro:property name="knee_height" value="0.150" /> <!-- From this is the thigh length -->
  <xacro:property name="wheel_radius" value="0.025" />
  <xacro:property name="wheel_length" value="0.025" />
  <xacro:property name="wheel_mass" value="0.100" />

  <xacro:include filename="$(find wheeled_biped_description)/models/inertial_macros.xacro" />
  <!-- Import all Gazebo-customization elements, including Gazebo colors -->
  <xacro:include filename="$(find wheeled_biped_description)/models/model.gazebo.xacro" />
  <!-- Import Rviz colors -->
  <xacro:include filename="$(find wheeled_biped_description)/models/materials.xacro" />

  <xacro:include filename="$(find wheeled_biped_description)/models/ros2_control.xacro" />

  <!-- Base Link -->
  <link name="base_link">

  </link>

  <joint name="head_joint" type="fixed">
    <parent link="base_link"/>
    <child link="head_link"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </joint>

  <link name="head_link">
    <xacro:inertial_box mass="${head_mass}" x="${head_size}" y="${head_size}" z="${head_height}">
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </xacro:inertial_box>

    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
	    <box size="${head_size} ${head_size} ${head_height}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
	    <box size="${head_size} ${head_size} ${head_height}"/>
      </geometry>
      <material name="orange"/>
    </visual>
  </link>

  <joint name="imu_joint" type="fixed">
    <parent link="head_link"/>
    <child link="imu_link"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </joint>

  <link name="imu_link">
    <collision>
      <geometry>
	    <box size="0.001 0.001 0.001"/>
      </geometry>
    </collision>

    <visual>
      <geometry>
	    <box size="0.001 0.001 0.001"/>
      </geometry>
      <material name="orange"/>
    </visual>

    <xacro:inertial_box mass="0.002" x="0.001" y="0.001" z="0.001">
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </xacro:inertial_box>
  </link>

  <joint name="upper_left_leg_joint" type="revolute">
    <parent link="head_link"/>
    <child link="upper_left_leg_link"/>
    <origin xyz="0 ${head_size/2} 0" rpy="${-pi/2} 0 0"/>
    <axis xyz="0 0 1"/>
    <dynamics damping="0.5"/>
    <limit lower="0" upper="${pi/2}" effort="30" velocity="${pi}"/>
  </joint>

  <link name="upper_left_leg_link">
    <collision>
      <geometry>
	    <cylinder radius="0.025" length="0.01"/>
      </geometry>
    </collision>

    <visual>
      <geometry>
	    <cylinder radius="0.025" length="0.01"/>
      </geometry>
      <material name="grey"/>
    </visual>

    <xacro:inertial_cylinder mass="${joint_mass}" radius="0.025" length="0.025">
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </xacro:inertial_cylinder>
  </link>

  <joint name="lower_left_leg_joint" type="revolute">
    <parent link="upper_left_leg_link"/>
    <child link="lower_left_leg_link"/>
    <origin xyz="0 ${knee_height} 0" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <dynamics damping="0.5"/>
    <limit lower="0" upper="${pi}" effort="30" velocity="${pi}"/>
  </joint>

  <link name="lower_left_leg_link">
    <collision>
      <geometry>
	    <cylinder radius="0.025" length="0.01"/>
      </geometry>
    </collision>

    <visual>
      <geometry>
	    <cylinder radius="0.025" length="0.01"/>
      </geometry>
      <material name="grey"/>
    </visual>

    <xacro:inertial_cylinder mass="${joint_mass}" radius="0.025" length="0.025">
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </xacro:inertial_cylinder>
  </link>

  <joint name="left_wheel_joint" type="continuous">
    <parent link="lower_left_leg_link"/>
    <child link="left_wheel_link"/>
    <origin xyz="0 ${knee_height} 0" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <dynamics damping="0.5"/>
  </joint>

  <link name="left_wheel_link">
    <collision>
      <geometry>
	    <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
      </geometry>
    </collision>

    <visual>
      <geometry>
	    <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
      </geometry>
      <material name="black"/>
    </visual>

    <xacro:inertial_cylinder mass="${wheel_mass}" radius="${wheel_radius}" length="${wheel_length}">
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </xacro:inertial_cylinder>
  </link>

    <joint name="upper_right_leg_joint" type="revolute">
    <parent link="head_link"/>
    <child link="upper_right_leg_link"/>
    <origin xyz="0 ${-head_size/2} 0" rpy="${-pi/2} 0 0"/>
    <axis xyz="0 0 1"/>
    <dynamics damping="0.5"/>
    <limit lower="0" upper="${pi/2}" effort="30" velocity="${pi}"/>
  </joint>

  <link name="upper_right_leg_link">
    <collision>
      <geometry>
	    <cylinder radius="0.025" length="0.01"/>
      </geometry>
    </collision>

    <visual>
      <geometry>
	    <cylinder radius="0.025" length="0.01"/>
      </geometry>
      <material name="grey"/>
    </visual>

    <xacro:inertial_cylinder mass="${joint_mass}" radius="0.025" length="0.025">
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </xacro:inertial_cylinder>
  </link>

  <joint name="lower_right_leg_joint" type="revolute">
    <parent link="upper_right_leg_link"/>
    <child link="lower_right_leg_link"/>
    <origin xyz="0 ${knee_height} 0" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <dynamics damping="0.5"/>
    <limit lower="0" upper="${pi}" effort="30" velocity="${pi}"/>
  </joint>

  <link name="lower_right_leg_link">
    <collision>
      <geometry>
	    <cylinder radius="0.025" length="0.01"/>
      </geometry>
    </collision>

    <visual>
      <geometry>
	    <cylinder radius="0.025" length="0.01"/>
      </geometry>
      <material name="grey"/>
    </visual>

    <xacro:inertial_cylinder mass="${joint_mass}" radius="0.025" length="0.025">
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </xacro:inertial_cylinder>
  </link>

  <joint name="right_wheel_joint" type="continuous">
    <parent link="lower_right_leg_link"/>
    <child link="right_wheel_link"/>
    <origin xyz="0 ${knee_height} 0" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <dynamics damping="0.5"/>
  </joint>

  <link name="right_wheel_link">
    <collision>
      <geometry>
	    <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
      </geometry>
    </collision>

    <visual>
      <geometry>
	    <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
      </geometry>
      <material name="black"/>
    </visual>

    <xacro:inertial_cylinder mass="${wheel_mass}" radius="${wheel_radius}" length="${wheel_length}">
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </xacro:inertial_cylinder>
  </link>
</robot>
